---
title: "토비의 스프링(4) - 예외"
date: 2021-02-16T23:55:30-04:00
categories:
  - Spring
tags:
  - Spring
  - Java
---

이 포스팅은 [토비의 스프링 3.1]의 4장 "예외"의 내용을 바탕으로 작성했다.

# 초난감 예외처리

## 예외 블랙홀

초기의 코드를 작성하다보면 예외처리를 제대로 하지 않고 넘어가는 경우가 발생할 수 있다. IDE에서 표시되는 에러를 해결하기 위해 try~catch로 처리를 하긴 하지만, 본래의 로직 구현에만 초점이 맞춰져 있고, 예외에 대해 신경쓰지 않는 경우가 이에 해당한다.

```java
try {
...
}
catch(SQLException e) {
}
```

위의 코드처럼 예외를 잡고 아무처리 하지 않는것은 절대 만들어서는 안되는 코드다. (단, 예외 발생을 무시하고 정상적인 상황인것처럼 다음 라인으로 넘어가겠다는 분명한 의도가 있다면 상관없겠지만, 이런 의도를 갖고 코드를 짜는 상황이 있을까 싶다.)

위와 같은 코드에서는 프로그램 실행중에 어디선가 오류로 인해 예외가 발생했는데도 그것을 무시하고 계속 진행이 되버린다. 그로 인해, 어떤 기능이 비정상적으로 동작하거나, 메모리 혹은 리소스가 소진되거나, 예상치 못한 다른 문제가 발생할 것이다. 최종적으로 오작동을 하거나 시스템 오류가 나서 운영자가 알아차렸을때는 이미 조치를 취하기엔 너무 늦었다.(시스템 이상의 원인이 무엇인지 찾아내기가 매우 힘들다)

아래의 코드들도 위의 코드와 크게 다를바 없다

```java
try { ... } catch(SQLException e) {
	System.out.println(e);
}

try { ... } catch(SQLException e) {
	e.printStackTrace();
}
```

개발중에는 계획된 시나리오로 테스트를 진행하면서 콘솔창이나 터미널에서 이 메세지를 바로 확인하고 소스의 수정 및 조취를 취할 수 있다. 하지만 운영서버에선 어떨까? 누군가가 계속 콘솔 로그를 모니터링 하면서 예외를 확인할 수는 없다. 그렇기 때문에 이는 심각한 폭탄으로 남아 있을 것이다.

예외가 발생하면 적절히 처리가 돼야 하는데, 위의 방법은 그저 메세지를 출력하는것일뿐 아무 처리가 되지 않는다.

예외를 처리할 때 반드시 지켜야 할 원칙은 **"모든 예외는 적절하게 복구되든지 아니면 작업을 중단시키고 운영자 또는 개발자에게 분명하게 통보돼야 한다"** 라는 것이다.

SQLException의 경우 SQL문법 에러, 데이터 엑세스 로직에 심각한 버그 존재,  서버 다운, 네트워크 문제 등의 심각한 상황이 발생한다. 이런 경우에 예외를 무시하고 아무 문제 없는듯이 다음 코드의 실행을 이어간다는 것은 말이 되지 않는다. 콘솔이나 로그에 예외 메세지를 출력하는 건 아무 도움이 안된다.

토비님에 의하면 아무것도 안할바에 차라리 아래와 같은게 나을것이다.

```java
} catch(SQLException e) {
	e.printStackTrace();
	System.exit(1);
}
```

물론 실전에선 이렇게 하면 안된다.(sql수행중에 예외로 인해 시스템자체가 다운되는건 말이 안된다고 생각한다). 위 코드의 의도는 **예외를 무시하거나 잡아먹어 버리는 코드는 만들지 말라**는 것이다. 굳이 예외를 잡아서 뭔가 조치를 취할 방법이 없다면 잡지 말아야 한다.(메소드 선언부에 throws SQLException을 선언해서 자신을 호출한 코드에 예외처리 책임을 전가해라)

## 무의미하고 무책임한 throws

catch블록으로 예외를 잡아도 딱히 처리할 방법도 없고, JDK API나 라이브러리에서 던지는 각종 예외를 매번 throws로 선언하기 귀찮아서 아래와 같이 throws Exception을 기계적으로 붙이는 경우가 종종 있다.(예외 클래스들의 최상위 클래스인 Exception으로 몽땅 처리해버리면, 각종 상세 예외들을 일일히 나열하지 않아도 돼서 편하긴 하다)

```java

public void method1() throws Exception {
	method2();
}

public void method2() throws Exception {
	method3();
}

public void method3() throws Exception { ...
}
```

위의 코드처럼 기계적으로 throws Exception을 넣는것은 무엇이 문제일까? 자신이 사용하려는 메소드에 throws Exception이 선언돼있다고 상상해보자. IDE에서 에러가 표시돼어 try~catch로 예외를 처리를 하려고 해도 어떤 예외가 발생하는지 아무 정보를 얻을 수 없다. 정말 무엇인가 실행중에 뭔지는 모르겠지만 예외적인 상황이 발생할 수 있다는 것인지, 아니면 그냥 습관적으로 복붙하다 남은 throws 선언문인지 알 수가 없다. 실제로 의미있는 예외를 던지기 위해 선언됐다고 하더라도 어떤 예외인지 알기 어렵다(보통 예외이름만 봐도 예외에 대해 추측이 가능하지만 Exception만으론 정보가 부족하다).  그래서 이런 메소드를 사용하게 된다면, 동일하게 throws Exception을 선언하게 될 수 밖에 없다. 결과적으로 적절한 처리를 통해 복구될 수 있는 예외상황도 제대로 다룰 수 있는 기회를 박탈당한다.

# 예외의 종류와 특징

//작성중